export const countryList = [
    ["Afghanistan", "Asia"],
    ["Argentina", "South America"],
    ["Australia", "Oceania"],
    ["Austria", "Europe"],
    ["Belgium", "Europe"],
    ["Brazil", "South America"],
    ["Cambodia", "Asia"],
    ["Canada", "North America"],
    ["China", "Asia"],
    ["Croatia", "Europe"],
    ["Cuba", "North America"],
    ["Dominican Republic", "North America"],
    ["Ecuador", "South America"],
    ["El Salvador", "North America"],
    ["Ethiopia", "Africa"],
    ["Finland", "Europe"],
    ["France", "Europe"],
    ["Germany", "Europe"],
    ["Greenland", "Europe"],
    ["Guam", "Oceania"],
    ["Guatemala", "North America"],
    ["Haiti", "North America"],
    ["Hungary", "Europe"],
    ["Iceland", "Europe"],
    ["India", "Asia"],
    ["Ireland", "Europe"],
    ["Israel", "Asia"],
    ["Italy", "Europe"],
    ["Japan", "Asia"],
    ["Kenya", "Africa"],
    ["Latvia", "Europe"],
    ["Lebanon", "Asia"],
    ["Malawi", "Africa"],
    ["Malaysia", "Asia"],
    ["Mexico", "North America"],
    ["Netherlands", "Europe"],
    ["Nigeria", "Africa"],
    ["Norway", "Europe"],
    ["Pakistan", "Asia"],
    ["Poland", "Europe"],
    ["Portugal", "Europe"],
    ["Romania", "Europe"],
    ["Saudi Arabia", "Asia"],
    ["Spain", "Europe"],
    ["Sweden", "Europe"],
    ["Switzerland", "Europe"],
    ["Taiwan", "Asia"],
    ["Thailand", "Asia"],
    ["Uganda", "Africa"],
    ["Ukraine", "Europe"],
    ["United States of America", "North America"],
    ["Venezuela", "South America"],
    ["Zimbabwe", "Africa"]
];
